/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    id ("org.springframework.boot") version "2.2.4.RELEASE"
    id("io.spring.dependency-management") version "1.1.0"
    // * NOTE: http://localhost:8080/actuator/info
    id("com.gorylenko.gradle-git-properties") version "2.4.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter:2.2.4.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-web:2.2.4.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.2.4.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.2.4.RELEASE")
    implementation("org.liquibase:liquibase-core:3.8.6")
    runtimeOnly("com.h2database:h2:1.4.200")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.2.4.RELEASE")
}

group = "com.tomgregory"
version = "0.0.1-SNAPSHOT"
description = "maven-to-gradle"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

// gitProperties {
//     keys = ['git.commit.id']
// }